# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kgb9IAoyJxmyBcSZ8tLzKeT-GIPvPqHE
"""

import pandas as pd
import requests
import json

columns = ["Country", "Capital", "Population"]
df = pd.DataFrame(columns=columns)

while True:
    user_input = input("Enter a country name (lowercase, no spaces), or 'stop' to stop: ")
    if user_input.lower() == "stop":
        break

    url = f"https://restcountries.com/v3.1/name/{user_input}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        capital = data[0]["capital"]
        population = data[0].get("population", "N/A")

        df = df.append({"Country": user_input, "Capital": capital, "Population": population}, ignore_index=True)
        print(f"Capital: {capital}")
        print(f"Population: {population}")
    else:
        print(f"API call failed with status code {response.status_code}")

output_file = "countries_data.json"
df.to_json(output_file, orient="records")

print(f"Data saved to {output_file}")